"""
CryptoResearchLab — Backtesting Engine
Event-driven backtester with realistic cost modeling, walk-forward validation,
and strict no-future-leakage enforcement.
"""
import logging
from dataclasses import dataclass, field
from typing import Callable, Optional

import numpy as np
import pandas as pd

from config import BacktestConfig, RiskConfig
from engine.metrics import StrategyMetrics, compute_metrics, compute_walk_forward_metrics, compute_oos_degradation

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════
# SIGNAL / TRADE STRUCTURES
# ═══════════════════════════════════════════════════════════════

@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    timestamp: int  # unix ms
    side: str  # "long" or "short"
    strength: float = 1.0  # 0-1, used for position sizing
    strategy: str = ""
    reason: str = ""
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    time_stop_hours: Optional[int] = None
    metadata: dict = field(default_factory=dict)


@dataclass
class Trade:
    """A completed trade."""
    entry_time: int
    exit_time: int
    side: str
    entry_price: float
    exit_price: float
    size: float  # in quote currency
    pnl_gross: float
    commission: float
    slippage: float
    pnl_net: float
    exit_reason: str = ""  # "take_profit", "stop_loss", "time_stop", "signal_exit"
    strategy: str = ""

    def to_dict(self) -> dict:
        return {
            "entry_time": self.entry_time,
            "exit_time": self.exit_time,
            "side": self.side,
            "entry_price": self.entry_price,
            "exit_price": self.exit_price,
            "size": self.size,
            "pnl_gross": self.pnl_gross,
            "commission": self.commission,
            "slippage": self.slippage,
            "pnl_net": self.pnl_net,
            "exit_reason": self.exit_reason,
            "strategy": self.strategy,
        }


# ═══════════════════════════════════════════════════════════════
# POSITION TRACKER
# ═══════════════════════════════════════════════════════════════

@dataclass
class Position:
    """An open position."""
    entry_time: int
    side: str
    entry_price: float
    size: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    time_stop_hours: int = 48
    strategy: str = ""


# ═══════════════════════════════════════════════════════════════
# BACKTESTER
# ═══════════════════════════════════════════════════════════════

class Backtester:
    """
    Event-driven backtester with realistic cost modeling.

    Strategy interface:
        strategy_fn(df, bar_idx, open_position) -> Optional[Signal]

    The strategy receives the FULL DataFrame + current bar index.
    Strategies MUST only access df.iloc[:bar_idx+1] — no future leakage
    is enforced by convention (strategies use bar_idx as upper bound).
    This avoids creating O(n) DataFrame slices per bar.
    """

    def __init__(
        self,
        config: BacktestConfig,
        risk_config: RiskConfig,
    ):
        self.config = config
        self.risk_config = risk_config

    def _apply_slippage(self, price: float, side: str, is_entry: bool) -> float:
        """Apply slippage: adverse direction for entries, adverse for exits."""
        slip_pct = self.config.slippage_bps / 10000
        if (side == "long" and is_entry) or (side == "short" and not is_entry):
            return price * (1 + slip_pct)
        else:
            return price * (1 - slip_pct)

    def _compute_commission(self, notional: float) -> float:
        return notional * self.config.commission_rate

    def _compute_position_size(
        self,
        equity: float,
        price: float,
        atr_value: float,
        signal_strength: float = 1.0,
    ) -> float:
        """Compute position size based on risk config."""
        if self.risk_config.sizing_method == "fixed_pct":
            return equity * self.config.max_position_pct * signal_strength

        elif self.risk_config.sizing_method == "volatility_scaled":
            if atr_value <= 0 or price <= 0:
                return equity * self.config.max_position_pct * 0.5
            # Scale position so that a 1-ATR move = target vol fraction of equity
            daily_vol_pct = atr_value / price
            annual_vol = daily_vol_pct * np.sqrt(365)
            target_size = equity * (self.risk_config.vol_target_annualized / max(annual_vol, 0.01))
            return min(target_size, equity * self.config.max_position_pct) * signal_strength

        elif self.risk_config.sizing_method == "kelly":
            return equity * self.risk_config.kelly_fraction * self.config.max_position_pct * signal_strength

        return equity * self.config.max_position_pct * signal_strength

    def run(
        self,
        df: pd.DataFrame,
        strategy_fn: Callable,
        strategy_name: str = "unnamed",
    ) -> tuple[pd.DataFrame, pd.Series, StrategyMetrics]:
        """
        Run backtest on a single data segment.

        Args:
            df: OHLCV + features DataFrame
            strategy_fn: function(df_up_to_bar, bar_idx, position) -> Optional[Signal]
            strategy_name: name for logging

        Returns:
            (trades_df, equity_curve, metrics)
        """
        equity = self.config.initial_capital
        equity_curve = []
        trades = []
        position: Optional[Position] = None

        # Need ATR for position sizing
        has_atr = "atr_14" in df.columns

        # Warm-up period: skip first 50 bars
        warmup = 50

        for i in range(warmup, len(df)):
            current_bar = df.iloc[i]
            timestamp = int(current_bar["timestamp"])
            price = float(current_bar["close"])

            # ─── Check exits for open position ───
            if position is not None:
                exit_signal = False
                exit_reason = ""
                exit_price = price

                # Stop loss
                if position.stop_loss is not None:
                    if position.side == "long" and float(current_bar["low"]) <= position.stop_loss:
                        exit_price = position.stop_loss
                        exit_signal = True
                        exit_reason = "stop_loss"
                    elif position.side == "short" and float(current_bar["high"]) >= position.stop_loss:
                        exit_price = position.stop_loss
                        exit_signal = True
                        exit_reason = "stop_loss"

                # Take profit
                if not exit_signal and position.take_profit is not None:
                    if position.side == "long" and float(current_bar["high"]) >= position.take_profit:
                        exit_price = position.take_profit
                        exit_signal = True
                        exit_reason = "take_profit"
                    elif position.side == "short" and float(current_bar["low"]) <= position.take_profit:
                        exit_price = position.take_profit
                        exit_signal = True
                        exit_reason = "take_profit"

                # Time stop
                if not exit_signal:
                    hours_held = (timestamp - position.entry_time) / 3_600_000
                    if hours_held >= position.time_stop_hours:
                        exit_signal = True
                        exit_reason = "time_stop"

                # Strategy exit signal
                if not exit_signal:
                    # Pass full df + bar_idx (strategies enforce no-leakage via bar_idx)
                    signal = strategy_fn(df, i, position)
                    if signal is not None and signal.side != position.side:
                        exit_signal = True
                        exit_reason = "signal_exit"

                if exit_signal:
                    # Execute exit
                    exit_price_slipped = self._apply_slippage(exit_price, position.side, False)
                    commission = self._compute_commission(position.size)
                    slippage_cost = abs(exit_price - exit_price_slipped) * (position.size / exit_price)

                    if position.side == "long":
                        pnl_gross = (exit_price_slipped - position.entry_price) / position.entry_price * position.size
                    else:
                        pnl_gross = (position.entry_price - exit_price_slipped) / position.entry_price * position.size

                    pnl_net = pnl_gross - commission - slippage_cost

                    trade = Trade(
                        entry_time=position.entry_time,
                        exit_time=timestamp,
                        side=position.side,
                        entry_price=position.entry_price,
                        exit_price=exit_price_slipped,
                        size=position.size,
                        pnl_gross=pnl_gross,
                        commission=commission,
                        slippage=slippage_cost,
                        pnl_net=pnl_net,
                        exit_reason=exit_reason,
                        strategy=strategy_name,
                    )
                    trades.append(trade)
                    equity += pnl_net
                    position = None

            # ─── Check for new entry ───
            if position is None:
                signal = strategy_fn(df, i, None)

                if signal is not None:
                    atr_val = float(current_bar.get("atr_14", price * 0.02)) if has_atr else price * 0.02
                    size = self._compute_position_size(equity, price, atr_val, signal.strength)

                    entry_price = self._apply_slippage(price, signal.side, True)
                    entry_commission = self._compute_commission(size)
                    equity -= entry_commission  # pay commission on entry

                    # Set stop/take profit
                    sl = signal.stop_loss
                    tp = signal.take_profit
                    if sl is None:
                        if signal.side == "long":
                            sl = entry_price - self.risk_config.stop_loss_atr_mult * atr_val
                        else:
                            sl = entry_price + self.risk_config.stop_loss_atr_mult * atr_val
                    if tp is None:
                        if signal.side == "long":
                            tp = entry_price + self.risk_config.take_profit_atr_mult * atr_val
                        else:
                            tp = entry_price - self.risk_config.take_profit_atr_mult * atr_val

                    position = Position(
                        entry_time=timestamp,
                        side=signal.side,
                        entry_price=entry_price,
                        size=size,
                        stop_loss=sl,
                        take_profit=tp,
                        time_stop_hours=signal.time_stop_hours or self.risk_config.time_stop_hours,
                        strategy=strategy_name,
                    )

            # Record equity
            # Mark-to-market if position open
            mtm_equity = equity
            if position is not None:
                if position.side == "long":
                    unrealized = (price - position.entry_price) / position.entry_price * position.size
                else:
                    unrealized = (position.entry_price - price) / position.entry_price * position.size
                mtm_equity += unrealized

            equity_curve.append({"timestamp": timestamp, "equity": mtm_equity})

        # Close any remaining position at last bar
        if position is not None:
            last_price = float(df.iloc[-1]["close"])
            exit_price_slipped = self._apply_slippage(last_price, position.side, False)
            commission = self._compute_commission(position.size)
            slippage_cost = abs(last_price - exit_price_slipped) * (position.size / last_price)
            if position.side == "long":
                pnl_gross = (exit_price_slipped - position.entry_price) / position.entry_price * position.size
            else:
                pnl_gross = (position.entry_price - exit_price_slipped) / position.entry_price * position.size
            pnl_net = pnl_gross - commission - slippage_cost
            trades.append(Trade(
                entry_time=position.entry_time,
                exit_time=int(df.iloc[-1]["timestamp"]),
                side=position.side,
                entry_price=position.entry_price,
                exit_price=exit_price_slipped,
                size=position.size,
                pnl_gross=pnl_gross,
                commission=commission,
                slippage=slippage_cost,
                pnl_net=pnl_net,
                exit_reason="end_of_data",
                strategy=strategy_name,
            ))

        # Build results
        trades_df = pd.DataFrame([t.to_dict() for t in trades]) if trades else pd.DataFrame()
        eq_df = pd.DataFrame(equity_curve)
        eq_series = pd.Series(
            eq_df["equity"].values,
            index=pd.to_datetime(eq_df["timestamp"], unit="ms"),
        ) if len(eq_df) > 0 else pd.Series(dtype=float)

        metrics = compute_metrics(
            trades_df, eq_series,
            initial_capital=self.config.initial_capital,
            strategy_name=strategy_name,
        )

        return trades_df, eq_series, metrics


# ═══════════════════════════════════════════════════════════════
# WALK-FORWARD VALIDATOR
# ═══════════════════════════════════════════════════════════════

class WalkForwardValidator:
    """
    Walk-forward validation for time series strategies.
    Splits data into rolling train/val/test windows.
    """

    def __init__(
        self,
        config: BacktestConfig,
        risk_config: RiskConfig,
        train_days: int = 60,
        val_days: int = 15,
        test_days: int = 15,
    ):
        self.backtester = Backtester(config, risk_config)
        self.train_days = train_days
        self.val_days = val_days
        self.test_days = test_days

    def _split_by_time(
        self, df: pd.DataFrame
    ) -> list[tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]]:
        """
        Create walk-forward folds.
        Each fold: [train_window | val_window | test_window]
        Windows slide forward by test_window size.
        """
        tf_ms = df["timestamp"].diff().median()
        candles_per_day = 86_400_000 / tf_ms

        train_bars = int(self.train_days * candles_per_day)
        val_bars = int(self.val_days * candles_per_day)
        test_bars = int(self.test_days * candles_per_day)
        fold_size = train_bars + val_bars + test_bars
        step_size = test_bars

        folds = []
        start = 0
        while start + fold_size <= len(df):
            train = df.iloc[start: start + train_bars].copy().reset_index(drop=True)
            val = df.iloc[start + train_bars: start + train_bars + val_bars].copy().reset_index(drop=True)
            test = df.iloc[start + train_bars + val_bars: start + fold_size].copy().reset_index(drop=True)
            folds.append((train, val, test))
            start += step_size

        return folds

    def validate(
        self,
        df: pd.DataFrame,
        strategy_fn: Callable,
        strategy_name: str = "unnamed",
    ) -> dict:
        """
        Run full walk-forward validation.

        Returns dict with:
            - fold_results: list of per-fold metrics
            - aggregate: aggregated metrics
            - is_robust: whether strategy passes robustness checks
            - oos_degradation: average OOS degradation
        """
        folds = self._split_by_time(df)
        if not folds:
            logger.warning("Not enough data for walk-forward validation")
            return {
                "fold_results": [],
                "aggregate": StrategyMetrics(),
                "is_robust": False,
                "oos_degradation": 100.0,
            }

        fold_results = []
        oos_degradations = []

        for i, (train, val, test) in enumerate(folds):
            logger.info(f"Walk-forward fold {i + 1}/{len(folds)}")

            # Run on train (in-sample)
            _, _, train_metrics = self.backtester.run(train, strategy_fn, f"{strategy_name}_train_f{i}")
            train_metrics.dataset_label = "train"

            # Run on val (validation / parameter selection)
            _, _, val_metrics = self.backtester.run(val, strategy_fn, f"{strategy_name}_val_f{i}")
            val_metrics.dataset_label = "val"

            # Run on test (true out-of-sample)
            trades, eq, test_metrics = self.backtester.run(test, strategy_fn, f"{strategy_name}_test_f{i}")
            test_metrics.dataset_label = "test"

            # OOS degradation
            degradation = compute_oos_degradation(train_metrics, test_metrics)
            oos_degradations.append(degradation)
            test_metrics.oos_degradation_pct = degradation
            test_metrics.oos_sharpe = test_metrics.sharpe_ratio

            fold_results.append({
                "fold": i,
                "train": train_metrics,
                "val": val_metrics,
                "test": test_metrics,
            })

        # Aggregate OOS results
        oos_metrics = [f["test"] for f in fold_results]
        aggregate = compute_walk_forward_metrics(oos_metrics)
        aggregate.oos_degradation_pct = float(np.mean(oos_degradations))

        # Robustness check
        is_robust = (
            aggregate.sharpe_ratio >= self.backtester.config.min_sharpe * 0.8
            and aggregate.max_drawdown_pct <= self.backtester.config.max_drawdown_pct
            and aggregate.total_trades >= self.backtester.config.min_trades
            and aggregate.oos_degradation_pct <= self.backtester.config.max_oos_degradation_pct
            and aggregate.profit_factor > 1.0
        )

        return {
            "fold_results": fold_results,
            "aggregate": aggregate,
            "is_robust": is_robust,
            "oos_degradation": float(np.mean(oos_degradations)),
        }
